dist: trusty
sudo: false

language: node_js

node_js:
- node
services:
- docker

addons:
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable

before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -g greenkeeper-lockfile@1

before_script:
- npm install -g --silent @angular/cli
- npm install
- greenkeeper-lockfile-update

script:
- ng build --prod

after_script:
- greenkeeper-lockfile-upload

notifications:
  email:
    on_failure: change
    on_success: change

env:
  global:
    secure: hPQ2rFJuva3rg+nsuf/pIW9DCSl/b+nPDCwjpN8Dm/926tbpRDqFejcArx9glzYrF2LiAf2l/QL1HlBhIwTrWIPKASiGQGlfSn67ldmoQiF94hTWE2AZw4KR6JuQ/8qrTvhfsDr4zdUE4DJlaAbDTMn+s2C9GyGskmM7NiLBFZU0erLeApxrWuKcbArHfZRmqjVR+Dcs+IIoBbTPAyikcWcKIodfcpNJpaEFqJ884horicr1xk4V8yjxMGNfGz0gX/T3ZBa5dZvt46Sa7F9ipW9+9ouAU5MtbKB3V81PsmsEZZUZdj34MMNEYaOHei+whIS+IOn4QGMD05Kd7P3PFhHyk+A/L4ZABUTcU4F/JZ8vGENcMHMCOpY/RXWzy1XlqEPW3Vgn3acxnAdz/PMqn05h+sM5Z4BZ/iT2PvWJfrAmtqqHKtCmuETEKAjLEl26HNnzzdU/ONe4TQwzu+kEYqhal0pnMLDh+5YILJkY5HiflKor6f1VOPBRy60o5gZIVgL4og5fY+tueJlU7mbYJfJckokHOFyIFETq9xDZZC76Hnsh7V4o7b+pjB6RlwhVBBkXpogb2/JLbNLQDuutDncIoteg7BxtZQ/PL7GU5GfO7Fvv3mZVs0ESG0tyBaOPii5WH2i02VMabIHopKt8avrSkaAyAbfMpsGxlQsXn64=
